#!/bin/bash
echo "✅ Static analysis"
ruff check .
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Static analysis failed, push aborted."
  exit $status
fi
echo "🧪 Running tests before push..."
pytest --quiet
status=$?
if [ $status -ne 0 ]; then
  echo "❌ Tests failed, push aborted."
  exit $status
fi
rm -rf error
echo "✅ Tests passed, pushing..."
