name: GH Actions Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Sanity check
        shell: pwsh
        run: Write-Host "GitHub Actions works 🎉"
