name: Run payments

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Clone browser repo
      run: |
        git clone https://x-access-token:${{ secrets.BROWSER_REPO_TOKEN }}@github.com/grzegorz-ozanski/browser.git

    - name: Install GitHub CLI
      uses: cli/cli-action@v2

    - name: Download Chrome i Chromedriver from GitHub Release
      run: |
        CHROMEDRIVER_VERSION=chromedriver-chrome-134.0.6944.0
        gh release download "${CHROMEDRIVER_VERSION}" \
          --repo grzegorz-ozanski/chrome \
          --pattern "${CHROMEDRIVER_VERSION}.zip"
         unzip ${CHROMEDRIVER_VERSION}.zip
      env:
        GH_TOKEN: ${{ secrets.CHROME_REPO_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add dependency to PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/browser" >> $GITHUB_ENV

    - name: Run the script
      run: python main.py
