name: Run payments on Linux

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron: "5 0,6,12,18 * * *"  # 4 times a day
  workflow_dispatch:
    inputs:
      dump:
        description: 'Dump workspace after job?'
        required: false
        default: 'false'

jobs:
  linux:
    uses: ./.github/workflows/run-payments.yml
    permissions:
      contents: write
    with:
      runner_label: '["self-hosted", "Linux"]'
      dump: ${{ inputs.dump }}
      event_name: ${{ github.event_name }}
    secrets:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GMAIL_EMAIL_ADDRESS: ${{ secrets.GMAIL_EMAIL_ADDRESS }}
      BROWSER_REPO_TOKEN: ${{ secrets.BROWSER_REPO_TOKEN }}
      CHROME_REPO_TOKEN: ${{ secrets.CHROME_REPO_TOKEN }}
      TESTDATA_PAT: ${{ secrets.TESTDATA_PAT }}
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
