name: Run payments on Linux

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron: "5 0,6,12,18 * * *"  # 4 times a day
  workflow_dispatch:
    inputs:
      dump:
        description: 'Dump workspace after job?'
        required: false
        default: 'false'

jobs:
  linux:
    uses: ./.github/workflows/run-payments.yml
    permissions:
      contents: write
    with:
      runner_label: '["self-hosted", "Linux"]'
      dump: ${{ inputs.dump }}
      event_name: ${{ github.event_name }}
