name: Run payments

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "5 0,6,12,18 * * *"  # 4 times a days
  workflow_dispatch:
    inputs:
      dump:
        description: 'Dump workspace after job?'
        required: false
        default: 'false'
env:
  GH_ACTIONS_USER_NAME: "github-actions"
  GH_ACTIONS_EMAIL: "github-actions@github.com"
  STATUS_FILE: .github/status/last-status.txt
  GH_TOKEN: ${{ secrets.CHROME_REPO_TOKEN }}
  LIBRARY: .github/scripts/functions.ps1
  COMPARE_SCRIPT: .github/scripts/compare-output.ps1
  MASK_SCRIPT: .github/scripts/mask-env-secrets.ps1
  SCRIPT_OUTPUT: script_output.txt
#  SCRIPT_OUTPUT: .github/data/test_output.txt
  REFERENCE_OUTPUT: .github/data/reference_output.txt
  REFERENCE_CONTENT: reference.txt
  ACTUAL_CONTENT: actual.txt
  DIFF_FILE: diff.txt
  CHROMEDRIVER_VERSION: chromedriver-chrome-134.0.6944.0

jobs:
#  run-ubuntu:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout current repo
#      uses: actions/checkout@v4
#
#    - name: Clone browser repo
#      run: |
#        git clone https://x-access-token:${{ secrets.BROWSER_REPO_TOKEN }}@github.com/grzegorz-ozanski/browser.git
#
#    - name: Install GitHub CLI
#      uses: cli/cli-action@v2
#
#    - name: Download Chrome i Chromedriver from GitHub Release
#      run: |
#        CHROMEDRIVER_VERSION=chromedriver-chrome-134.0.6944.0
#        gh release download "${CHROMEDRIVER_VERSION}" \
#          --repo grzegorz-ozanski/chrome \
#          --pattern "${CHROMEDRIVER_VERSION}.zip"
#         unzip ${CHROMEDRIVER_VERSION}.zip
#      env:
#        GH_TOKEN: ${{ secrets.CHROME_REPO_TOKEN }}
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Add dependency to PYTHONPATH
#      run: echo "PYTHONPATH=$(pwd)/browser" >> $GITHUB_ENV
#
#    - name: Run the script
#      run: python main.py
#

  run-windows:
    runs-on: [self-hosted, Windows]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Read previous status
      id: readstatus
      shell: pwsh
      run: |
        $file = "${env:STATUS_FILE}"
        if (Test-Path $file) {
          $value = Get-Content $file -Raw
          echo "previous=$value" >> ${env:GITHUB_OUTPUT}
        } else {
          Write-Error "Previous status file not found in '${env:STATUS_FILE}'!"
        }

    - name: Use system Python 3.11
      if: runner.os == 'Windows'
      run: |
        $PYTHONPATH = "$env:USERPROFILE/AppData/Local/Programs/Python/Python311"
        echo "$PYTHONPATH" >> $env:GITHUB_PATH

    - name: Verify system Python 3.11
      run: |
        python --version
        where python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Clone browser repo
      uses: actions/checkout@v4
      with:
        repository: grzegorz-ozanski/browser
        path: browser
        token: ${{ secrets.BROWSER_REPO_TOKEN }}

    - name: Download Chrome and Chromedriver from GitHub Release
      run: |
        gh release download ${env:CHROMEDRIVER_VERSION} `
          --repo grzegorz-ozanski/chrome `
          --pattern "${env:CHROMEDRIVER_VERSION}.zip"
        Expand-Archive -Path "${env:CHROMEDRIVER_VERSION}.zip" -DestinationPath .

    - name: Prepare environment
      run: |
        # Add dependency to PYTHONPATH
        echo "PYTHONPATH=$(pwd)/browser" >> $env:GITHUB_ENV
        # Prepare credentials
        echo "${{ secrets.CREDENTIALS }}" >> $env:GITHUB_ENV
        # Mask credentials
        pwsh -File $env:MASK_SCRIPT "_USERNAME,_PASSWORD" "${{ secrets.CREDENTIALS }}" 

    - name: "[SKIP REASON] Run the script skipped"
      if: ${{ contains(env.SCRIPT_OUTPUT, 'test_') }}
      run: |
        echo "::notice ::Skipping 'Run the script' step because 'env.SCRIPT_OUTPUT' contains 'test_."

    - name: Run the script
      if: ${{ ! contains(env.SCRIPT_OUTPUT, 'test_') }}
      continue-on-error: true
      shell: pwsh
      run: |
        python main.py 2>&1 | ForEach-Object { `
          Write-Host $_ `
          $_ `
        } | Set-Content program.log ${env:SCRIPT_OUTPUT}


    - name: Compare script output with reference
      id: compare
      shell: pwsh
      run: |
        pwsh -File ${env:COMPARE_SCRIPT} `
        ${env:SCRIPT_OUTPUT} `
        ${env:REFERENCE_OUTPUT} `
        -ComparedActual ${env:ACTUAL_CONTENT} `
        -ComparedExpected ${env:REFERENCE_CONTENT} `
        -Diff ${env:DIFF_FILE}

    - name: Upload error logs
      uses: actions/upload-artifact@v4
      with:
        name: error-logs
        if-no-files-found: ignore
        path: |
          ./error/**

    - name: Upload trace logs
      uses: actions/upload-artifact@v4
      with:
        name: trace-logs
        path: |
          ./trace/**

    - name: "[SKIP REASON] Upload log skipped"
      if: steps.compare.outputs.status == 'unchanged'
      run: |-
        echo "::notice ::Skipping 'Upload log if script output is different than reference' step " + 
             "because steps.compare.outputs.status == 'unchanged''."

    - name: Upload log if script output is different than reference
      if: steps.compare.outputs.status == 'changed'
      uses: actions/upload-artifact@v4
      with:
        name: changed-output
        path: |
          ${{ env.SCRIPT_OUTPUT }}
          ${{ env.ACTUAL_CONTENT }}
          ${{ env.REFERENCE_CONTENT }}
          ${{ env.DIFF_FILE }}

    # 🔁 Compare current workflow status with the previous one
    - name: Compare workflow status
      id: statuscheck
      if: always()
      shell: pwsh
      run: |
        if ("${{ steps.compare.outputs.status }}" -eq "changed") {
          $current = "failure"
        } elseif ("${{ steps.compare.outputs.status }}" -eq "unchanged") {
          $current = "success"
        } else {
          $current = "unknown"
        }

        $previous = "${{ steps.readstatus.outputs.previous }}"

        Write-Host "Previous: $previous"
        Write-Host "Current: $current"

        "current=${current}" >> $env:GITHUB_OUTPUT
        "previous=${previous}" >> $env:GITHUB_OUTPUT
        if ($previous -ne $current) {
          "changed=true" >> $env:GITHUB_OUTPUT
        } else {
          "changed=false" >> $env:GITHUB_OUTPUT
        }

        if ($previous -eq "failure") {
          $emoji = "❌"
          if ($current -eq "success") {
            "transition=FIXED" >> $env:GITHUB_OUTPUT
          }
        } elseif ($previous -eq "success") {
          $emoji = "✅"
          if ($current -eq "failure") {
            "transition=BROKEN" >> $env:GITHUB_OUTPUT
          }
        } elseif ($previous -eq "unknown") {
          $emoji = "🆕"
          if ($current -eq "success") {
            "transition=FIXED" >> $env:GITHUB_OUTPUT
          } elseif ($current -eq "failure") {
            "transition=BROKEN" >> $env:GITHUB_OUTPUT
          }
        } else {
          $emoji = "❔"
          if ($current -eq "success") {
            "transition=FIXED" >> $env:GITHUB_OUTPUT
          } elseif ($current -eq "failure") {
            "transition=BROKEN" >> $env:GITHUB_OUTPUT
          }
        }
        
        @"
        # 🛠️ Workflow summary
        
        - **Previous run status**: $emoji $previous
        - **Current comparison status**: ${{ steps.compare.outputs.status }}
        - 📃**Script Output**:
        "@ | Add-Content -Path $env:GITHUB_STEP_SUMMARY
        Get-Content -Path ${env:SCRIPT_OUTPUT} | Add-Content -Path $env:GITHUB_STEP_SUMMARY

    - name: "[DEBUG] Would send email?"
      run: |
        if ("${{ steps.statuscheck.outputs.changed }}" -eq "true") {
          Write-Host "Email would be sent."
        } elseif ("${{ steps.statuscheck.outputs.changed }}" -eq "false") {
          Write-Host "Email would NOT be sent."
        } else {
          Write-Host "Unrecognized status: '${{ steps.statuscheck.outputs.changed }}'."
        }

    - name: "[SKIP REASON] Send email if workflow result changed"
      if: github.event_name != 'schedule' || steps.statuscheck.outputs.changed != 'true'
      run: |-
        echo "::notice ::Skipping 'Send email if script output comparison result changed' step because condition " + 
             "'github.event_name == 'schedule' && steps.statuscheck.outputs.changed == 'true' is not met'."

    # 💌 Send email only on status change
    - name: Send email if script output comparison result changed and run was scheduled
      if: github.event_name == 'schedule' && steps.statuscheck.outputs.changed == 'true'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "⚠️ ${{ github.repository }} - workflow ${{ steps.statuscheck.outputs.transition }}"
        to: ${{ secrets.GMAIL_EMAIL_ADDRESS }}
        from: GitHub Actions <no-reply@github.com>
        body: |
          ${{ github.repository }} GitHub Actions scheduled job execution status changed 
          from "${{ steps.statuscheck.outputs.previous }}" to "${{ steps.statuscheck.outputs.current }}"

          ➤ View artifact and logs:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

          If this was expected, consider updating ${{ env.REFERENCE_OUTPUT }}

    - name: "[SKIP REASON] Copy working directory skipped"
      if: github.event.inputs.dump != 'true'
      run: |
        echo "::notice ::Skipping 'Copy working directory for inspection' step because 'github.event.inputs.dump != 'true''."

    - name: Copy working directory for inspection
      if: github.event.inputs.dump == 'true'
      shell: pwsh
      env:
        WORKSPACE_DUMP_DIR: ${{ runner.os == 'Windows' && 'c:/actions-runner/jobs' || '/tmp/actions-runner/jobs' }}
      run: |
        $src = "$env:GITHUB_WORKSPACE"
        $dst = "${env:WORKSPACE_DUMP_DIR}\${{ github.run_id }}"
        mkdir -p $dst 
        Copy-Item -Path $src -Recurse -Destination $dst

    # 💾 Save current status
    - name: Save current status
      if: always()
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        Set-Content -Path ${env:STATUS_FILE} -Value "${{ steps.statuscheck.outputs.current }}" -Encoding UTF8
        git config user.name "${env:GH_ACTIONS_USER_NAME}"
        git config user.email "${env:GH_ACTIONS_EMAIL}"
        git add ${env:STATUS_FILE}
        if (git diff --cached --quiet) {
          Write-Host "No changes to commit."
        } else {
          Write-Host "Committing modified '${env:STATUS_FILE}' file."
          git commit -m "Update last run status [skip ci]"
          git push
        }

    - name: "[SKIP REASON] Fail workflow"
      if: steps.compare.outputs.status == 'unchanged'
      run: |-
        $msg = "::notice ::Skipping 'Fail workflow if script output is different than reference' step " +
               "because 'steps.compare.outputs.status == 'unchanged''"
        echo $msg

    - name: Fail workflow if script output is different than reference
      if: steps.compare.outputs.status == 'changed'
      shell: pwsh
      run: |
        Write-Error "❌ Output changed – failing the run."
