name: Run payments on Linux

on:
#  push:
#    branches: [ 'master', 'html-test' ]
  schedule:
    - cron: "5 6 * * *"  # Daily @7.05
  workflow_dispatch:

jobs:
  linux:
    if: github.repository == 'grzegorz-ozanski/payments'
    uses: ./.github/workflows/run-payments.yml
    permissions:
      contents: write
    with:
      runner_label: '["self-hosted", "Linux"]'
      event_name: ${{ github.event_name }}
      browser_profile_dir: '/runner/_work/payments'
    secrets:
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GMAIL_EMAIL_ADDRESS: ${{ secrets.GMAIL_EMAIL_ADDRESS }}
      BROWSER_REPO_TOKEN: ${{ secrets.BROWSER_REPO_TOKEN }}
      PAYMENTS_TESTDATA_REPO_TOKEN: ${{ secrets.TESTDATA_REPO_TOKEN }}
      CREDENTIALS: ${{ secrets.CREDENTIALS }}
      REPORTS_TS_HOST: ${{ secrets.REPORTS_TS_HOST }}
      REPORTS_TS_PORT: ${{ secrets.REPORTS_TS_PORT }}
      REPORTS_USER: ${{ secrets.REPORTS_USER }}
      REPORTS_SSH_KEY: ${{ secrets.REPORTS_SSH_KEY }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}
