#file: noinspection GrazieInspection
#  This workflow runs the payment script, compares results, and handles errors and reporting.
#  It is intended to be used via workflow_call from scheduled or manual dispatch workflows.
name: Run payments

on:
  workflow_call:
    inputs:
      event_name:
        description: 'Event name (push/schedule/etc)'
        required: false
        type: string
      browser_profile_dir:
        description: 'Persistent browser profile dir location'
        required: false
        default: ''
        type: string
      runner_label:
        description: 'Label of the runner to use'
        required: true
        default: '["self-hosted", "Linux"]'
        type: string
      debug_workflow:
        required: false
        default: false
        type: boolean
    secrets:
      GMAIL_USERNAME:
        required: true
      GMAIL_APP_PASSWORD:
        required: true
      GMAIL_EMAIL_ADDRESS:
        required: true
      BROWSER_REPO_TOKEN:
        required: true
      PAYMENTS_TESTDATA_REPO_TOKEN:
        required: true
      CREDENTIALS:
        required: true
      REPORTS_TS_HOST:
        required: true
      REPORTS_TS_PORT:
        required: true
      REPORTS_USER:
        required: true
      REPORTS_SSH_KEY:
        required: true

jobs:
  run-payments:
    # noinspection GrazieInspection
    # Ignore inspection error on '.github' folder name (as the proper service name is apparently GitHub)
    env:
      ACTUAL_CONTENT:          actual.txt
      BROWSER_LOG_FILENAME:    ${{ inputs.debug_workflow && format('{0}/testdata/test_trace.log', github.workspace) || 'trace.log' }}
      BROWSER_LOG_TO_CONSOLE:  false
      DEBUG_WORKFLOW:          ${{ inputs.debug_workflow }}
      DIFF_FILE:               diff.txt
      GH_ACTIONS_EMAIL:       "github-actions@github.com"
      GH_ACTIONS_USER_NAME:   "github-actions"
      LOCAL_ARTIFACTS_WINDOWS: Z:/github-runner/artifacts
      LOCAL_ARTIFACTS_LINUX:   /runner/artifacts
      REFERENCE_CONTENT:       reference.txt
#      REFERENCE_OUTPUT:        ${{ github.workspace }}/testdata/reference_output.txt
      REFERENCE_OUTPUT:        ${{ github.workspace }}/testdata/reference_output.txt
      SCRIPT_OUTPUT:           ${{ inputs.debug_workflow && format('{0}/testdata/test_output.txt', github.workspace) || 'script_output.txt' }}
      SCRIPT_HTML:             script_output.html
      STATUS_FILE:             ${{ github.workspace }}/testdata/last-status.txt
      TEST_DATA:               ${{ github.workspace }}/testdata

      # Scripts
      COMPARE_SCRIPT:       .github/scripts/compare-output.ps1
      GIT_PUSH_SCRIPT:      .github/scripts/git-push.ps1
      MASK_SCRIPT:          .github/scripts/mask-env-secrets.ps1
      READ_STATUS_SCRIPT:   .github/scripts/read-previous-status.ps1
      STATUS_SCRIPT:        .github/scripts/compare-status.ps1
      STORE_LOCALLY_SCRIPT: .github/scripts/store-artifacts-locally.ps1
      UPLOAD_SCRIPT:        .github/scripts/upload-artifacts-sftp.ps1

    runs-on: ${{ fromJson(inputs.runner_label) }}

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    defaults:
      run:
        working-directory: payments

    steps:
    - name: Checkout current repo (payments) into subdir
      uses: actions/checkout@v4
      with:
        path: payments

    - name: Read previous status
      id: readstatus
      shell: pwsh
      run: |
        pwsh -File ${env:READ_STATUS_SCRIPT} "${env:STATUS_FILE}" "${env:GITHUB_OUTPUT}"

    - name: "[SKIP REASON] Configure and run the script steps skipped"
      if: ${{ contains(env.SCRIPT_OUTPUT, 'test_') }}
      shell: pwsh
      run: |
        echo "::notice ::Skipping all configuration steps and 'Run the script' step because 'env.SCRIPT_OUTPUT' contains 'test_."

    - name: Use system Python 3.11
      if: ${{ runner.os == 'Windows' && !contains(env.SCRIPT_OUTPUT, 'test_') }}
      shell: pwsh
      run: |
        $PYTHONPATH = "$env:USERPROFILE/AppData/Local/Programs/Python/Python311"
        echo "$PYTHONPATH" >> $env:GITHUB_PATH

    - name: Verify system Python 3.11
      if: ${{ !contains(env.SCRIPT_OUTPUT, 'test_') }}
      shell: pwsh
      run: |
        python --version
        (Get-Command python).Source

    - name: Clone required browser repo
      if: ${{ !contains(env.SCRIPT_OUTPUT, 'test_') }}
      uses: actions/checkout@v4
      with:
        repository: grzegorz-ozanski/browser
        path: browser
        token: ${{ secrets.BROWSER_REPO_TOKEN }}

    - name: Install dependencies
      if: ${{ !contains(env.SCRIPT_OUTPUT, 'test_') }}
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Prepare environment
      if: ${{ !contains(env.SCRIPT_OUTPUT, 'test_') }}
      shell: pwsh
      run: |
        # Add dependency to PYTHONPATH
        echo "PYTHONPATH=$env:GITHUB_WORKSPACE/browser" >> $env:GITHUB_ENV
        # Prepare credentials
        echo "${{ secrets.CREDENTIALS }}" >> $env:GITHUB_ENV
        # Mask credentials
        pwsh -File $env:MASK_SCRIPT "_USERNAME,_PASSWORD" "${{ secrets.CREDENTIALS }}"
        # Store credentials if running on self-hosted runner (PAYMENTS_CREDENTIALS_STORE_FILE is set)
        if ($env:PAYMENTS_CREDENTIALS_STORE_FILE) {
          $path = ${env:PAYMENTS_CREDENTIALS_STORE_FILE}
          $dir  = Split-Path -Path $path -Parent
          if (-not (Test-Path -LiteralPath $dir -PathType Container)) {
              echo "::error:: Directory for PAYMENTS_CREDENTIALS_STORE_FILE '$path' does not exist: '$dir'\n" +
              "No credentials stored"
              return
          }
          $escaped = "${{ secrets.CREDENTIALS }}" -replace '(?m)^([^=\r\n]+)=(.+)$', '$1="$2"'
          Set-Content -LiteralPath $path -Value $escaped -NoNewline 
          if ($IsLinux -or $IsMacOS) {
              chmod 600 -- $path
              sed -i 's/^/export /' $path
          } elseif ($IsWindows) {
              icacls $path /inheritance:r | Out-Null
              icacls $path /grant:r "$env:USERNAME:(F)" | Out-Null
          }
        }

    - name: Download reference output from private repo
      uses: actions/checkout@v4
      with:
        repository: grzegorz-ozanski/payments-testdata
        path: ${{ env.TEST_DATA }}
        token: ${{ secrets.PAYMENTS_TESTDATA_REPO_TOKEN }}

    - name: Run the script
      if: ${{ !contains(env.SCRIPT_OUTPUT, 'test_') }}
      continue-on-error: true
      shell: pwsh
      run: |
        python -u -m payments -v -t -o ${env:SCRIPT_OUTPUT} --persistent-profile-dir "${{inputs.browser_profile_dir}}" -p actum,nordhome,opec

    - name: Generate HTML output
      continue-on-error: true
      shell: pwsh
      run: |
        python payments/html_output.py -o ${env:SCRIPT_OUTPUT} -l ${{ env.BROWSER_LOG_FILENAME }} -H ${{ env.SCRIPT_HTML }} -n

    - name: Compare script output with reference
      id: compare
      shell: pwsh
      run: |
        pwsh -File ${env:COMPARE_SCRIPT} `
        ${env:SCRIPT_OUTPUT} `
        ${env:REFERENCE_OUTPUT} `
        -ComparedActual ${env:ACTUAL_CONTENT} `
        -ComparedExpected ${env:REFERENCE_CONTENT} `
        -Diff ${env:DIFF_FILE}

    - name: Upload error logs
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: error-logs
        if-no-files-found: ignore
        retention-days: 3
        path: |
          payments/error/**

    - name: Upload trace logs
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: trace-logs
        retention-days: 3
        path: |
          payments/${{ env.BROWSER_LOG_FILENAME }}
          payments/trace/**

    - name: "[SKIP REASON] Upload log skipped"
      if: steps.compare.outputs.status == 'unchanged'
      shell: pwsh
      run: |-
        echo "::notice ::Skipping 'Upload log if script output is different than reference' step " + 
             "because steps.compare.outputs.status == 'unchanged''."

    - name: Upload log if script output is different than reference
      if: steps.compare.outputs.status == 'changed'
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: changed-output
        retention-days: 3
        path: |
          payments/${{ env.SCRIPT_OUTPUT }}
          payments/${{ env.ACTUAL_CONTENT }}
          payments/${{ env.REFERENCE_CONTENT }}
          payments/${{ env.DIFF_FILE }}

    - name: Store artifacts locally
      shell: pwsh
      env:
        COMPARE_STATUS: ${{ steps.compare.outputs.status }}
        LOCAL_ARTIFACTS_DIR: ${{ runner.os == 'Windows' && env.LOCAL_ARTIFACTS_WINDOWS || env.LOCAL_ARTIFACTS_LINUX }}
      run: |
        $artifactPaths = @(
          "./error",
          "$env:BROWSER_LOG_FILENAME",
          "./trace"
        )
        if ($env:COMPARE_STATUS -eq 'changed') {
          $artifactPaths += @(
            "$env:SCRIPT_OUTPUT",
            "$env:ACTUAL_CONTENT",
            "$env:REFERENCE_CONTENT",
            "$env:DIFF_FILE"
          )
        }
        pwsh -File ${env:STORE_LOCALLY_SCRIPT} `
        -WorkflowName $env:GITHUB_WORKFLOW `
        -RunNumber $env:GITHUB_RUN_NUMBER `
        -JobName $env:GITHUB_JOB `
        -Artifacts "$artifactPaths" `
        -TargetDir $env:LOCAL_ARTIFACTS_DIR

    - name: Check reports SFTP reachable
      id: reports
      shell: bash
      run: |
        if nc -zv -w 3 "${{ secrets.REPORTS_TS_HOST }}" ${{ secrets.REPORTS_TS_PORT }}; then
          echo "reachable=true" >> "$GITHUB_OUTPUT"
        else
          echo "reachable=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Start ssh-agent
      if: steps.reports.outputs.reachable == 'true'
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.REPORTS_SSH_KEY }}

    - name: Upload logs to SFTP
      if: steps.reports.outputs.reachable == 'true'
      shell: pwsh
      env:
        SFTP_HOST: ${{ secrets.REPORTS_TS_HOST }}
        SFTP_PORT: ${{ secrets.REPORTS_TS_PORT }}   # np. 22
        SFTP_USER: ${{ secrets.REPORTS_USER }}   # np. uploader
        REMOTE_DIR: upload/logs
      run: |
        $errDir = "error"
        $errLogs = "error-logs.zip"
        $errFiles = @()
        $artifactPaths = @()
        
        if (Test-Path $errDir) {
          $errFiles = Get-ChildItem -Path $errDir -Recurse -File -ErrorAction SilentlyContinue
        }
        if ($errFiles.Count -gt 0) {
          Compress-Archive -Path $errDir -DestinationPath $errLogs -Force
          $artifactPaths += "$errLogs"
        } else {
          Write-Host "No error logs — skipping $errLogs"
        }

        $paths = @(
          "$env:BROWSER_LOG_FILENAME",
          "trace"
        )        
        $traceLogs = "trace-logs.zip"
        Compress-Archive -Path $paths -DestinationPath $traceLogs -Force
        $artifactPaths += "$traceLogs"
        
        pwsh -File ${env:UPLOAD_SCRIPT} `
          -WorkflowName $env:GITHUB_WORKFLOW `
          -RunNumber $env:GITHUB_RUN_NUMBER `
          -JobName $env:GITHUB_JOB `
          -Artifacts $artifactPaths `
          -SftpHost $env:SFTP_HOST `
          -SftpPort ([int]$env:SFTP_PORT) `
          -SftpUser $env:SFTP_USER `
          -RemoteBaseDir $env:REMOTE_DIR `
          -SummaryBaseUrl "https://${{ env.REPORTS_TS_HOST }}/logs"

    - name: Upload log if script output is different than reference
      if: steps.compare.outputs.status == 'changed'
      shell: pwsh
      run: |
        $paths = @(
          "${{ env.SCRIPT_OUTPUT }}",
          "${{ env.ACTUAL_CONTENT }}",
          "${{ env.REFERENCE_CONTENT }}",
          "${{ env.DIFF_FILE }}"
        )
        Compress-Archive -Path $paths -DestinationPath changed-output.zip -Force
        
        $artifactPaths = @("changed-output.zip")
        pwsh -File ${env:UPLOAD_SCRIPT} `
          -WorkflowName $env:GITHUB_WORKFLOW `
          -RunNumber $env:GITHUB_RUN_NUMBER `
          -JobName $env:GITHUB_JOB `
          -Artifacts $artifactPaths `
          -SftpHost $env:SFTP_HOST `
          -SftpPort ([int]$env:SFTP_PORT) `
          -SftpUser $env:SFTP_USER `
          -RemoteBaseDir $env:REMOTE_DIR `
          -SummaryBaseUrl "https://${{ env.REPORTS_TS_HOST }}/artifacts"

    # 🔁 Compare current workflow status with the previous one
    - name: Compare workflow status and set workflow summary
      id: statuscheck
      if: always()
      shell: pwsh
      run: |
        pwsh -File ${env:STATUS_SCRIPT} `
        "${{ steps.readstatus.outputs.previous }}" `
        "${{ steps.compare.outputs.status }}" `
        ${env:SCRIPT_HTML} `
        ${env:DIFF_FILE} `
        ${env:GITHUB_OUTPUT} `
        ${env:GITHUB_STEP_SUMMARY}

    - name: "[SKIP REASON] Send email if workflow result changed"
      if: inputs.event_name != 'schedule' || steps.statuscheck.outputs.changed != 'true'
      shell: pwsh
      run: |-
        echo "::notice ::Skipping 'Send email if script output comparison result changed' step because condition " + 
             "'github.event_name == 'schedule' && steps.statuscheck.outputs.changed == 'true' is not met'."

    - name: Prepare email body
      if: |
        (inputs.event_name == 'schedule' && steps.statuscheck.outputs.transition != 'NONE')
        || steps.statuscheck.outputs.transition == 'FIXED'
      id: emailbody
      shell: pwsh
      run: |
        $body = @"
        ${{ github.repository }} GitHub Actions scheduled job execution status changed
        from "${{ steps.statuscheck.outputs.previous }}" to "${{ steps.statuscheck.outputs.current }}"
    
        ➤ View artifact and logs:
        https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        "@
    
        if ("${{ steps.statuscheck.outputs.transition }}" -ne "FIXED") {
            $body += @"

        If this was expected, consider updating ${{ env.REFERENCE_OUTPUT }}
        "@
        }
        "body<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        $body       | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        "EOF"       | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    # 💌 Send email only on status change
    - name: Send email if script output comparison result changed and run was scheduled
      if: |
        (inputs.event_name == 'schedule' && steps.statuscheck.outputs.transition != 'NONE')
        || steps.statuscheck.outputs.transition == 'FIXED'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: "⚠️ ${{ github.repository }} - workflow ${{ steps.statuscheck.outputs.transition }}"
        to: ${{ secrets.GMAIL_EMAIL_ADDRESS }}
        from: GitHub Actions <no-reply@github.com>
        body: ${{ steps.emailbody.outputs.body }}

    # 💾 Save current status
    - name: Save current status
      if: always()
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.PAYMENTS_TESTDATA_REPO_TOKEN }}
      run: |
        if ("${{ steps.statuscheck.outputs.current }}" -ne "") {
          $status="${{ steps.statuscheck.outputs.current }}"
        } else {
          $status="failure"
          Write-Warning "Empty status check step output, defaulting to $status!"
        }
        Set-Content -Path ${env:STATUS_FILE} -Value "$status" -Encoding UTF8
        
        pwsh -File ${env:GIT_PUSH_SCRIPT} `
        -File ${env:STATUS_FILE} `
        -Message "Update coverage badge [skip ci]" `
        -Username ${env:GH_ACTIONS_USER_NAME} `
        -Email ${env:GH_ACTIONS_EMAIL} `
        -RepoDir ${env:TEST_DATA}

    - name: "[SKIP REASON] Fail workflow"
      if: steps.compare.outputs.status == 'unchanged'
      shell: pwsh
      run: |-
        $msg = "::notice ::Skipping 'Fail workflow if script output is different than reference' step " +
               "because 'steps.compare.outputs.status == 'unchanged''"
        echo $msg

    - name: Fail workflow if script output is different than reference
      if: steps.compare.outputs.status == 'changed'
      shell: pwsh
      run: |
        Write-Error "❌ Output changed – failing the run."
