name: Run unit tests

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone required browser repo
        uses: actions/checkout@v4
        with:
          repository: grzegorz-ozanski/browser
          path: browser
          token: ${{ secrets.BROWSER_REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Install Pyright
        run: npm install -g pyright

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report

      - name: Generate HTML coverage report
        if: always()
        run: |
          coverage html
          zip -r htmlcov.zip htmlcov/

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: htmlcov
          path: htmlcov.zip

      - name: Add coverage report to summary
        if: always()
        run: |
          echo '### 🧪 Test Coverage Summary' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          coverage report >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Add mypy results to summary
        if: always()
        run: |
          echo '### ✅ Static Analysis Summary' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          mypy . --strict --ignore-missing-imports >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Add pyright results to summary
        if: always()
        run: |
          echo '### ✅ Pyright Summary' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          pyright >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

