name: Run unit tests

on:
  push:
    branches: [ '*' ]
  pull_request:

env:
  LOCAL_ARTIFACTS_DIR: /runner/artifacts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=payments --cov=providers --cov=lookuplist --cov-report=term

      - name: Generate HTML coverage report
        if: always()
        run: |
          pytest --cov=payments --cov=providers --cov=lookuplist --cov-report=html
          zip -r htmlcov.zip htmlcov/

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: htmlcov
          path: htmlcov.zip

      - name: Store artifacts locally
        shell: pwsh
        env:
          COMPARE_STATUS: ${{ steps.compare.outputs.status }}
          LOCAL_ARTIFACTS_DIR: ${{ runner.os == 'Windows' && env.LOCAL_ARTIFACTS_WINDOWS || env.LOCAL_ARTIFACTS_LINUX }}
        run: |
          $artifactPaths = @(
            "./htmlcov.zip"
          )
          pwsh -File .github/scripts/store-artifacts-locally.ps1 `
          -WorkflowName $env:GITHUB_WORKFLOW `
          -RunNumber $env:GITHUB_RUN_NUMBER `
          -JobName $env:GITHUB_JOB `
          -Artifacts "$artifactPaths" `
          -TargetDir $env:LOCAL_ARTIFACTS_DIR
